### ISSUE TITLE
Dataset Not Available

### ISSUE THREAD

**Issue by topksampler** [AliMaleky7997/DL_Project#1]
Hey there! Can you kindly make the dataset available. I did download data from the main website. However, there is some variation in the directory structure and file naming to the one you used.

**Comment by AliMaleky7997** [comment]
Hi There, you can find the dataset in the following link:

https://drive.google.com/file/d/1tPtWg3bj45J1hilFoqLxvYkQeX4fZp-l/view?usp=sharing

**Comment by topksampler** [comment]
Thank you @AliMaleky7997

**Comment by topksampler** [comment]
@AliMaleky7997, Can you tell me more about the data preprocessing you did to arrive at this dataset? This dataset is clean and tidy, both the text and images. The original dataset is very noisy, and when I tried working on that model, the model never converged.

**Comment by topksampler** [comment]
I used the dataset available [here](https://zenodo.org/record/56198#.V2p0KTXT6eA) and the preprocessing scripts mentioned [here](https://github.com/harvardnlp/im2markup)

**Comment by AliMaleky7997** [comment]
Hi @lalith1403, sorry for the delay. I did this project a few years ago and unfortunately, I don't quite remember the exact transformations I used for preprocessing. I think cropping to the exact formula bounding box and then resizing back to the original size was one of them, but I don't remember anything more. I should have written it down somewhere, my bad.

Did the model converge when you worked with my version of the dataset? If so, why not use it?

**Comment by topksampler** [comment]
The model does converge... But, for some strange reason, the same thing does not converge on a large dataset with more noise in it. For now, I have used your dataset for training. However, the same model fails with the noisier dataset. I am unable to figure out where exactly I am going wrong.

**Comment by AliMaleky7997** [comment]
Unfortunately, I can't remember all the transformations I used for cleaning the data and I also do not have the code for it available.

**Comment by topksampler** [comment]
No worries. Thank you.
